# GitHub Pages Configuration
title: "LinkedIn Resume Generator"
description: "Professional resume generation from LinkedIn profiles with privacy compliance"
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
author:
  name: "Resume Owner"
  email: "contact@example.com"

# GitHub Pages specific settings
url: ""  # Will be set automatically by GitHub Pages
baseurl: ""  # Will be set automatically by GitHub Pages

# Social media links (optional)
github_username: ""
linkedin_username: ""

# Navigation
header_pages:
  - index.md

# Enable GitHub Pages features
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge