name: Generate Resume Files

on:
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'generate_resume.py'
      - 'src/**'

jobs:
  generate-resumes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Pandoc and LaTeX for professional PDF generation
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          texlive-latex-base \
          texlive-fonts-recommended \
          texlive-latex-extra \
          texlive-xetex \
          fonts-liberation \
          libpango-1.0-0 \
          libpangoft2-1.0-0 \
          libgdk-pixbuf2.0-0 \
          libffi-dev \
          libcairo2 \
          wkhtmltopdf
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Pandoc setup
      run: |
        python test_pandoc.py
        
    - name: Generate resume files
      run: |
        python generate_resume.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/resume.md docs/resume.pdf
        git diff --staged --quiet || git commit -m "Auto-update resume files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger main website update
      if: success()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/DiegoBarrosA/diegobarrosaraya.com/dispatches \
          -d '{"event_type":"resume-updated"}'